### ISSUE TITLE
suggestion: optimizing tile entities

### ISSUE THREAD

**Issue by Remu1012** [Akarin-project/Akarin#76]
i noticed that my tile entiys get lagging if  i 
got 1000 of them on a world

**Comment by CBM1014** [comment]
Thank you for your suggestion.

We had tried our best to make a high performance server software. Akarin had optimized the entity ticks and it actully almost achieved our goal.
You can try to update your Akarin first, to make sure you are using the Akarin which had all the optimizations.

 I did a performance test between Akarin and Paper. Based on testing, I found that Akarin has a better performance than Paper on entityticks. Here are the steps and results.

Test Envoriment:
 - Windows 10
 - Java 1.8 (x86)
 - Akarin and Paper server with 1G RAM and an completely empty world.

Steps:
 - Run `/timings on` command to reset timings.
 - Add 3000 vexes to the world, wait for the timings record the performance of entityticks about 5 minutes. Then, run command `/timings report`

Results:
 - Paper: `https://timings.aikar.co/?id=a96956f2009c47df9bcff609d4b1319b`
 - Akarin: `https://timings.aikar.co/?id=a7bdd6492d544effa46fcd5f4a24dd36`

The graph shows that at the first 2 minutes, Akarin has 2741 entities with 21% tps loss, Paper has 2426 entities (over 300 less than Akarin, it may caused by entity collector provided by spigot or bukkit) with 35% (15% more than Akarin) tps loss. After the amount of entities reduced to less than 2000, the performance of Paper and Akarin were almost the same (both 20tps and very low tps loss, close to 0).
The entity performance of Akarin is better than Paper overall, particularly when a huge amount of entities spawned at one time.

Entity ticks in Akarin 1.13.2 are not asynchronous. As for your situation, You can try to run Akarin with a better processer(with a newer architecture or higher frequency).  And we will continue to optimize server ticks as much as possible. Thank you for your support.

**Comment by shinohara-rin** [comment]
async entities possible?
I thought it would be easier to implement than async chunks or blocks

**Comment by Satella1012** [comment]
@shinohara-rin thnx for corecting my bad english :p
